### ISSUE TITLE
Don't `wp_die()` when EO is not active

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#1]
The current `is_active()` check is a bit heavy-handed. We can probably just bail out of the plugin and throw an admin notice.

**Comment by r-a-y** [comment]
+1

**Comment by christianwach** [comment]
Could also add a `Depends:` plugin header item? It's always a nice surprise to dependencies working when commons-in-a-box is active.

As a side note: it's a weird and humbling thing to watch a plugin being torn apart and rebuilt. I really should have attended to some of the more naive and embarrassing content before the process started!

**Comment by boonebgorges** [comment]
> Could also add a Depends: plugin header item? It's always a nice surprise to dependencies working when commons-in-a-box is active.

Yes, let's!

> As a side note: it's a weird and humbling thing to watch a plugin being torn apart and rebuilt. I really should have attended to some of the more naive and embarrassing content before the process started!

Ha, no embarrasment is necessary. You did all the hard exploratory work. Ray and I have the benefit of entering with all the research already done, and laid out in the codebase :)

**Comment by r-a-y** [comment]
> As a side note: it's a weird and humbling thing to watch a plugin being torn apart and rebuilt. I really should have attended to some of the more naive and embarrassing content before the process started!

What Boone said :)  We're just enhancing what you've already bulit a foundation for.

I think this plugin is going to rock once we're ready to release it!

**Comment by mkgold** [comment]
So excited about the work you are all doing. Many thanks!!

**Comment by BoweFrankema** [comment]
This is great! Great to see this take shape :-)
