### ISSUE TITLE
User event calendar - Single event permalinks

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/bp-event-organiser#13]
Currently, event permalinks displayed on a user's calendar resolve to EO's permalink - `example.com/events/event/POST-SLUG/`.

I think this makes sense for user-created events.  However, for group events displayed within a user's calendar, do we want these events to resolve to the first-matching group's single permalink? `example.com/groups/THE-GROUP/events/POST-SLUG/`

**Comment by boonebgorges** [comment]
Ideally, we should be resolving in a contextual way. Links to events on 
group calendar pages should point to (and resolve to) 
`/groups/group-name/events/event-name/`. As such, it should be possible 
to view single events at various URLs:
- example.com/events/event/post-slug
- example.com/groups/group-name/events/post-slug
- example.com/groups/some-other-group/events/post-slug

and so on for every associated group. This is important because it 
maintains the group header, nav, etc that the user expects when clicking 
on the event name from the group context.

In the case where this might cause confusion about duplicate content (to 
search engines? I dunno) we should use something like rel=canonical.

**Comment by r-a-y** [comment]
> Ideally, we should be resolving in a contextual way. Links to events on group calendar pages should point to (and resolve to) `/groups/group-name/events/event-name/`. As such, it should be possible to view single events at various URLs:
> - example.com/events/event/post-slug
> - example.com/groups/group-name/events/post-slug
> - example.com/groups/some-other-group/events/post-slug

Events displayed within a group's event calendar do work this way.

I was talking about from a user's calendar - `example.com/members/admin/events/`.  If a group event is shown on a user's calendar, currently it resolves to the default EO permalink, which kind of makes sense, but was wondering if the event permalink should resolve to a group's event permalink.

My question was more of a UX thing.

rel="canonical" sounds like a good thing to add on group event permalink pages.  If we implement this, it should use the original EO permalink.

**Comment by boonebgorges** [comment]
Ah, my bad. I guess I'd say:
- If the user is a member of at least one of the associated groups, 
  resolve that group
- Otherwise, resolve to the "canonical" URL

**Comment by boonebgorges** [comment]
I'm playing with this a little in the context of bp-nelo, and I think I'd like to suggest the following: When creating an event from within a user context, you should then be directed to `example.com/members/username/events/event-slug`. The styling for the single event page is very different from the user calendar/create event page, and I think it's jarring to be led out of the user nav/wrapper context after creation. What do you think?

**Comment by r-a-y** [comment]
> The styling for the single event page is very different from the user calendar/create event page, and I think it's jarring to be led out of the user nav/wrapper context after creation.

Yeah it is.  My original thinking is we do not show single blog posts within a user's profile either, but we are showing the "New Event" interface within a user's profile so that's probably where the disconnect is coming from.

I wasn't sure what we wanted to do here, so this is a good conversation to have.

**Comment by boonebgorges** [comment]
>  My original thinking is we do not show single blog posts within a user's profile either, but we are showing the "New Event" interface within a user's profile so that's probably where the disconnect is coming from.

Yeah, this sounds right. Then again, there is really no interface for viewing user blog posts within a user context at all, so I'm not sure that there's much parallel there. I think it's going to ease user confusion a lot if we can follow the general rule of keeping people in the same context (user vs group) when they click on stuff.

**Comment by r-a-y** [comment]
Will route user events under the user's profile.

> Then again, there is really no interface for viewing user blog posts within a user context at all, so I'm not sure that there's much parallel there.

The parallel is a user can create a blog post in the backend, but on the frontend, we do not display blog posts within the user's profile, although it would make sense to show them within the profile.  (Sidenote: I've been wanting to build a user frontend blog plugin for awhile now.  The WP_Frontend_Admin_Screen library would make part of this possible!)
