### ISSUE TITLE
Tag display seems to be buggy

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#15]
When creating an event, I added a tag 'bar', and when redirected to the event page, I now see:

> Tags: bundefineduundefinednundefineddundefinedeundefinedfundefinediundefinednundefinedeundefineddundefinedaundefined

I'm assuming this is happening because of some string vs object offset issue.

**Comment by r-a-y** [comment]
I think this is due to me developing on WP trunk for the admin 
abstraction and not WP 4.1.1.

Will look into it.

**Comment by boonebgorges** [comment]
If it's a WP bug, please let me know :-D

**Comment by r-a-y** [comment]
Can you try adding a new tag to a new event after pulling commit 41bb181?

**Comment by boonebgorges** [comment]
That was it :)

**Comment by r-a-y** [comment]
Sweet!
