### ISSUE TITLE
Links from single events back to calendar view

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#16]
I'm thinking it'd be nice for having a standardized UI for going "back" to calendar view when viewing a single event. (These would all be context-sensitive, going to the user/group/global calendar as appropriate.) Any ideas about how this should look?

**Comment by r-a-y** [comment]
On a group calendar's single event, there are the following links at the bottom of the page:

`Back | Edit | Delete` (Edit and Delete are dependent on user cap).

On EO's single event permalink, I didn't do anything because of the admin bar "Edit Event" link.

**Comment by boonebgorges** [comment]
The Back | Edit | Delete links look good. Let's duplicate them across 
contexts - it might be redundant with the admin bar, but I don't think 
anyone uses the admin bar, and in any case it's best to be consistent.
