### ISSUE TITLE
Featured image support for events

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#17]
It would be cool for events to support a featured image, which could then be displayed in various places (single event view, activity streams, etc). Does event-organiser support this already? If not, maybe it'd make for a good upstream improvement.

**Comment by stephenharris** [comment]
Events do support this, it can be toggled in the general settings tabd, but you can forceably enable it too since the array passed to `register_post_type()` is filtered. On the single event page no effort is made to display the image, it's left to the theme ala `single.php`.

**Comment by boonebgorges** [comment]
Awesome. That means we just have to enable this in our front-end 
creation interface, and then display it somehow in our templates.

**Comment by r-a-y** [comment]
This should be done in the recent commits.

Note: In the WP admin area, only users with the `'upload_files'` cap can add a featured image.  I have stuck to this guideline for now.  This means a user who is a subscriber or a contributor cannot add a featured image at the moment.

Should we dynamically give these users the `'upload_files'` cap only when creating or editing an event?

**Comment by boonebgorges** [comment]
Awesome - thanks, @r-a-y.

> Should we dynamically give these users the 'upload_files' cap only when creating or editing an event?

Yeah, if you can easily do this, please do. Prior art: https://github.com/boonebgorges/buddypress-docs/blob/master/includes/attachments.php#L36 https://github.com/boonebgorges/buddypress-docs/blob/master/includes/attachments.php#L597

**Comment by r-a-y** [comment]
This should be completed now.

The BP Docs meta cap example helped!

**Comment by boonebgorges** [comment]
@r-a-y The way this is currently built, users will see all items from the media library in the media modal. Is there a straightforward way to make this not happen? I kludge it in BuddyPress Docs like this https://github.com/boonebgorges/buddypress-docs/blob/master/includes/attachments.php#L394. 

I think we probably shouldn't ship it on the Commons as-is - there is the potential for confusion and perhaps privacy problems. If it's not easy to filter media library images, we should probably disable this feature for v1.

**Comment by r-a-y** [comment]
@boonebgorges I've added some code to filter attachments according to the logged-in user when selecting a "Featured Image" instead of by the current post as in BP Docs.

I also would have loved to put this in the WP Frontend Admin Screen library, but it's too late to add the filter in the class before WP can see it.

**Comment by boonebgorges** [comment]
:+1:

**Comment by r-a-y** [comment]
Forgot to close this one as well!
