### ISSUE TITLE
Future publishing of events

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#18]
Feature request for the future: the ability to create an event (post_status=future?) and then have it autopublished on a scheduled date.

**Comment by r-a-y** [comment]
I've ported the "Publish" metabox from the WP admin post interface to the frontend.

This should allow changing the publish date and WP should autopublish it with their cron system.  What needs testing is how future events can be edited from the calendar interface or from some other page (eg. `example.com/members/admin/events/scheduled-events/`)

**Comment by boonebgorges** [comment]
Ah, I hadn't even thought of just porting over the interface. I think this looks pretty good, though probably needs some styling. (Also - does draft saving work? If not, we should hide the button.)

**Comment by r-a-y** [comment]
It looks good in twenty-twelve :)

Haven't tested with bp-nelo or other themes yet.

**Comment by boonebgorges** [comment]
Ha. Everything looks good in twentytwelve!

Having the Publish button in the box also serves to deemphasize it a 
little bit. I wonder if we'd be better off hiding that as well, and 
moving it outside of the metabox.

**Comment by r-a-y** [comment]
Yeah, I was thinking about moving the "Publish" button out of the 
metabox as well.

Will do it now that I have someone else's feedback other than my own!

**Comment by r-a-y** [comment]
> (Also - does draft saving work? If not, we should hide the button.)

Yes, draft saving works, but at the moment, we do not have a frontend UI to manage these types of events -- future, drafts, trash.

As mentioned above, we need a place to list these types of events so the logged-in user can manage them.  Perhaps a URL like:

```
example.com/members/admin/events/unpublished/
```

Which we could use as a catch-all to list any event that is a draft, trashed or scheduled to be published in the future.  This page would be displayed as a table or list, not as a calendar.  Semi-related to #32.

**Comment by r-a-y** [comment]
I've added a first pass at managing unpublished events within a user's profile.

This is what it looks like in bp-nelo at the moment:

![Screenshot of a user's "Manage events" screen](https://cloud.githubusercontent.com/assets/505921/7324313/3208a8b4-ea6a-11e4-98df-3cc251c7145c.png)

Need to test with twentytwelve and other themes, but I think this works well for a first pass.  No support for pagination yet.

**Comment by boonebgorges** [comment]
Oh cool - this looks great. A 'Manage' tab makes sense. I wouldn't worry too much about pagination if it's complicated - just show all posts. I do think it'd make sense to limit the posts shown on this tab to those where the post_author is the logged-in user; using `bpeo_get_my_calendar_event_ids()` means that way more items will be returned (ie, group events), and in most cases these extra events will not be manageable by the user anyway. (Don't worry about bp_moderate users for now - they can use the dashboard.)

**Comment by r-a-y** [comment]
> I do think it'd make sense to limit the posts shown on this tab to those where the post_author is the logged-in user

Yeah, this was something I was thinking about over the weekend.  Will make the change.

**Comment by r-a-y** [comment]
Forgot to close this one!
