### ISSUE TITLE
User and group-specific iCal feeds

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#22]
It looks like this should be fairly easy - event-organiser has support for ical feeds already.

**Comment by stephenharris** [comment]
I think adding `?feed=eo-events` (or pretty permalink variant of) to any events page should do it. The iCal is registered as a feed with WordPress.

**Comment by r-a-y** [comment]
We have different requirements than EO, so I needed to create a helper function - `bpeo_do_ical_download()` (see commit 9b5c1d9) - that allows us to set the event query args and modify some properties in the iCalendar file.

I'm still using EO's native iCalendar generation class, but I'm using some filters to set some of the iCalendar properties like the name and URL.

Going to close this one.
