### ISSUE TITLE
Let's lose categories

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#29]
At least for CAC, we don't want both categories and tags. Let's just use tags.

**Comment by r-a-y** [comment]
We'll probably do this with a filter for CAC.  We don't want to intrude on anyone that might want categories for their implementation of events.

**Comment by r-a-y** [comment]
This is handled internally.

For those interested, this is the code snippet in use:

```
/**
 * Remove 'Categories' taxonomy for event post type.
 */
add_action( 'add_meta_boxes_event', function( $post ) {
    remove_meta_box( 'event-categorydiv', 'event', 'side' );
} );
```

**Comment by boonebgorges** [comment]
This is fine - thanks, @r-a-y. (Though, fwiw, I think that EO has 
enabled both categories and tags just because WP does it for posts; WP 
does it for posts only for historical reasons. It's hard for me to see 
the value in having both for events, in the majority of use cases. But I 
don't feel strongly about it.)
