### ISSUE TITLE
Taxonomy archives for group events

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#3]
Eg /groups/my-group/events/?category=foo

**Comment by r-a-y** [comment]
This is done.

You can now filter group events by:
- Category - `/groups/my-group/events/?cat=foo`
- Tag - `/groups/my-group/events/?tag=bar`

The term links on a group's single event page (`/groups/my-group/events/my-event/`) now use these links as well.
