### ISSUE TITLE
Secondary avatars not appearing consistently for multiple group associations

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#34]
When an event is associated with multiple groups, secondary avatars in the activity stream are only being inserted for the first of the groups. I kinda just wanna remove them all in the case of event activity.

**Comment by r-a-y** [comment]
I'd say remove it.

Or do something like this:

```
Action: Boone created the event "Awesome" in two groups.
Content: (this is dynamically generated) List of groups with avatar.
```

Crap, that wouldn't work due to the event content needing to be in the activity content... maybe prefixed to the event content?
