### ISSUE TITLE
Use consistent textdomain

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/bp-event-organiser#36]
The original BPEO plugin used `'bp-event-organizer'` as the textdomain:
https://github.com/christianwach/bp-event-organiser/search?utf8=%E2%9C%93&q=__&type=Code

This fork uses a mixture of the original and the UK spelling of `'bp-event-organiser'`.

We should decide on which textdomain to use before we're ready to release.

**Comment by boonebgorges** [comment]
WP protocol is to match the plugin slug (so that future automatic 
translation downloads will work.) bp-event-organiser FTW

**Comment by r-a-y** [comment]
:+1:
