### ISSUE TITLE
Deleted event activity item shouldn't link to anything

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/bp-event-organiser#37]
When an event is deleted, a new activity item is recorded in this format:

```
User (link) deleted the event "My Event" (link) in the group "My Group" (link)
```

We should probably remove the link from "My Event" since the link will 404.

**Comment by boonebgorges** [comment]
Yeah. And in fact, as I try to fix this, I see that once an event has been deleted, there's no great way to dynamically generate the action string. For the sake of expediency, I think I'm going to disable activity items related to event deletion for now. They don't seem very useful if there's nothing to click through to.
