### ISSUE TITLE
Undefined function in EO causing fatal error

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#44]
In https://github.com/stephenharris/Event-Organiser/commit/43365eeb93bacd7e7f096da2646, @stephenharris removed `eventorganiser_edit_init()`. We were piggybacking on this to build our frontend editing interface. I'm not sure whether this change is going to be merged into the mainline branch - it appears that it has not - but we should build a wrapper or something to avoid fatal errors.

**Comment by r-a-y** [comment]
Thanks for keeping up with EO's upstream changes.

It looks like we do not need to do the `elseif ( function_exists( '_eventorganiser_event_metaboxes_init' )` conditional since `_eventorganiser_event_metaboxes_init()` now runs on the proper `'add_meta_boxes_event'` hook, which our WP Frontend Admin Screen class should run properly.

**Comment by boonebgorges** [comment]
Ah, good catch. Make it so :)

**Comment by stephenharris** [comment]
@boonebgorges @r-a-y - just so you're aware, the `develop` branch on EO should be considered `3.0.0-alpha`. The next update (excluding any point releases) will be 3.0.0. There will be breaking changes in that release, but these will be largely UI changes, with API changes limited to removing long-deprecated behaviour. But there will also be internal changes such as these. There'll be a blog post summarising changes nearer the time, and a lengthy beta period too to iron out any issues.

**Comment by r-a-y** [comment]
Thanks for reaching out, @stephenharris.

We'll look for the blog post once 3.0.0-beta hits.

**Comment by stephenharris** [comment]
As promised: http://wp-event-organiser.com/blog/announcements/event-organiser-3-0-0-rc-1/  and a second post highlighting breaking changes: http://wp-event-organiser.com/blog/announcements/event-organiser-3-0-0-whats-changing/

**Comment by christianwach** [comment]
@stephenharris Thanks for the detailed post - very helpful. Look forward to the new version!
