### ISSUE TITLE
How to remove display events from private group in EO Events CPT feed

### ISSUE THREAD

**Issue by danaskallman** [cuny-academic-commons/bp-event-organiser#54]
Events that are added within a private group still appear on the events overall feed on a website, so at `https://yourdomain.com/events/event/feed` Is there a way to restrict private events from the CPT feed?

**Comment by boonebgorges** [comment]
Hi @danaskallman - Are you viewing this feed in a browser, as a logged-in user who has access to the private group? If so, you'll see the item; if not, you shouldn't see it. This is more or less by design - it's the same way that WP's `post_status` works in the context of a feed.

**Comment by danaskallman** [comment]
@boonebgorges right, yeah I was viewed as logged in. Thanks for getting back to me.
