### ISSUE TITLE
`post_status` of event associated with more than one group should default to most public of groups

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#55]
The logic for event `post_status` currently works like this: if the event is associated with at least one non-public group, the event gets `post_status` 'private'. We want this swapped: If the event is associated with at least one public group, it gets the `post_status` 'public'.

@r-a-y I think you originally wrote this - at least, the part on the front end that throws a dynamic message about the event being associated with a group. Could you please take a look?

**Comment by r-a-y** [comment]
Forgot to close this ticket!
