### ISSUE TITLE
Front-end event creation

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-event-organiser#6]
It should be possible to create events from the front end. This should use the metabox shim that @r-a-y has written. I think we should probably allow at least two endpoint types:
1. /groups/my-group/create-event/ (as discussed on the CAC ticket, this will help avoid slug conflicts)
2. Some non-group context. This could either be a top-level /create-event/, or perhaps a view inside of a user profile: /members/boonebgorges/create-event/

**Comment by r-a-y** [comment]
So, users currently create events at - `example.com/members/USER/events/new-event/`.

But, for groups, the URL is located at - `example.com/groups/GROUP/new-event/`.

I'm thinking I should revert my original idea of having group events created at `example.com/groups/GROUP/new-event/` and instead have them similar to users: `example.com/groups/GROUP/events/new-event`.

During save time, this will require some form of slug checking or making the single event slug unique.

**Comment by boonebgorges** [comment]
URL doesn't matter much to me personally, though I agree that we should be consistent.

I'm getting PHP notices when doing front-end editing - `Trying to get property of non-object in /home/bgorges/sites/wpmaster/wp-admin/includes/template.php on line 926` (`add_meta_box()` - `$page = $screen->id`). It looks like when you generate the taxonomy metaboxes in `WP_Frontend_Admin_Screen::display()`, you pass `null` to the `$screen` param, which causes `add_meta_box()` to check `get_current_screen()`, which is not set on the front end. I'm not sure what the right fix is - faking the current screen?

**Comment by r-a-y** [comment]
Hmm, I'm not seeing the notice during frontend editing on WP 4.1.1 and WP 4.2-bleeding.

>  It looks like when you generate the taxonomy metaboxes in WP_Frontend_Admin_Screen::display(), you pass null to the $screen param, which causes add_meta_box() to check get_current_screen(), which is not set on the front end. 

`get_current_screen()` should be set up during the `WP_Frontend_Admin_Screen::setup_abstraction()` method.

**Comment by boonebgorges** [comment]
No, I mean the function `get_current_screen()` exists, but it's returning `null`.

**Comment by r-a-y** [comment]
Hmm, maybe my attempt to be clever in the `setup_abstraction()` method is not working for all set ups.

What happens if you change the `$screen` parameter in the `add_meta_box()` call from `null` to `self::$post_type`?

**Comment by boonebgorges** [comment]
Aha, that does the trick!

**Comment by christianwach** [comment]
FYI, I'm getting `Warning: call_user_func() expects parameter 1 to be a valid callback, function 'post_thumbnail_meta_box' not found or invalid function name in /Users/needle/Sites/cbox/sites/cbox.eo.cmw/httpdocs/wp-content/plugins/bp-event-organiser/includes/wp-frontend-admin-screen/abstraction-metabox.php on line 202` when using this with a default CBOX install. It's appearing within a metabox titled "Slide Image", which would indicate an issue with CBOX's custom post type definitions. Will look into this further...

**Comment by r-a-y** [comment]
@christianwach Thanks for the report.  Should be fixed as of commit c5b302c.
