### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/bp-event-organiser#65]
Hi @boonebgorges,

The plugin version header is currently at `0.2` when we forked it from Christian's prior work.

We have two branches, `1.0.x` and `1.1.x`.  For CBOX, just want to clarify if we should bump the plugin version header to 1.0.0 or 1.1.0?  Probably the latter even though we never released a 1.0?

**Comment by boonebgorges** [comment]
Yup, I'd say the latter.

**Comment by r-a-y** [comment]
I've tagged version 1.1.0!  Going to close this one out.
